<?
    $APPLICATION->AddHeadScript('/bitrix/framework/js/jquery.js');
    $APPLICATION->AddHeadScript('/bitrix/framework/js/jquery.easing.1.3.js');
	$APPLICATION->AddHeadScript('/bitrix/framework/js/bootstrap.min.js');
	$APPLICATION->AddHeadScript('/bitrix/framework/js/jquery.fancybox.pack.js');
	$APPLICATION->AddHeadScript('/bitrix/framework/js/jquery.fancybox-media.js');
	$APPLICATION->AddHeadScript('/bitrix/framework/js/jcarousel/jquery.jcarousel.min.js');
	$APPLICATION->AddHeadScript('/bitrix/framework/js/jquery.nivo.slider.js');
	$APPLICATION->AddHeadScript('/bitrix/framework/js/bootstrap-datepicker.js');
	$APPLICATION->SetAdditionalCss('/bitrix/framework/css/bootstrap.css');
    $APPLICATION->SetAdditionalCss('/bitrix/framework/css/bootstrap-responsive.css');
    $APPLICATION->SetAdditionalCss('/bitrix/framework/css/fancybox/jquery.fancybox.css');
	$APPLICATION->SetAdditionalCss('/bitrix/framework/css/sliders.css');
	$APPLICATION->SetAdditionalCss('/bitrix/framework/css/font-awesome.css');
	$APPLICATION->SetAdditionalCss('/bitrix/framework/css/custom-fonts.css');
?>